### PR TITLE
Adds offset to items when dragging

### PR DESCRIPTION
**Pull request by guatedude2**
This PR adds offset to items when dragging so dragging appears seamless. This helps mitigate the issue when dragging an item, the item would center to the cursor and causing bad UX. 

N1VxZOoyPU

Related issues:
- https://github.com/ricardo-ch/react-easy-sort/issues/11

### CODE REVIEW

**Review by ValentinH — APPROVED** [review]

**Comment by ValentinH** [comment]
Thank you for bringing this cool improvement and also for the clean code!

**Comment by ValentinH** [comment]
This was published in v1.0.0. However, I had to revert it in v1.0.1. because I found a bug while integrating it on our website: it doesn't work if the container is not at the top-left of the window. You can see it on Storybook if you open the "docs" version.

Do you think you could have a look to have this fixed?

**Comment by ValentinH** [comment]
See : 
react-easy-sort-bug

**Comment by guatedude2** [comment]
Ah ok I’ll resubmit with the fix

**Comment by guatedude2** [comment]
Ok this PR should fix that https://github.com/ricardo-ch/react-easy-sort/pull/13

**Pull request merged**
